name: weekly-report

on:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install pandas requests

      - run: python scripts/weekly_report.py
